name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-build-pnpm-modules-cache-${{ hashFiles('**/package.json', 'pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-build-pnpm-modules-cache-
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 7.5.2
        run_install: true

    - name: Deploy
      env:
        GIT_AUTHOR_NAME: Github Actions
        GIT_COMMITTER_NAME: Github Actions
        GIT_AUTHOR_EMAIL: actions@github.com
        GIT_COMMITTER_EMAIL: actions@github.com
      run: |
        set -x
        pnpm build --outDir dist
        git fetch origin vercel
        git switch vercel
        mv dist/* api
        git checkout main package.json pnpm-lock.yaml
        git diff --quiet && [[ "$(git show -s --format=%s main)" != *'[deploy]' ]] && exit 0
        git add api package.json pnpm-lock.yaml
        git commit -m "update from workflow run #$GITHUB_RUN_NUMBER"
        git push
